ecopura_django/ecopuraApp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import logout_then_login
from ecopuraApp.views import *
from usuarios.views import *


app_name= 'ecopuraApp'
#APP_NAME ME SIRVE PARA PODER UTILIZAR EL REVERSE_LAZY, DICIENDOLE QUE APP VAMOS A USAR Y EL NOMBRE (name='contacto_url')
#DE LA URL A LA  QUE VAMOS REDIRECCIONAR
urlpatterns = [
    #PRIMER PARAMETRO PARA EL DIRECCIONAR CON URL, Y EL SEGUNDO ES EL NOMBRE DE LA FUNCION 
    #QUE ESTA EN LAS VISTAS (NO OLVIDAR IMPORTARLAS).
    path('',Inicio.as_view(),name='inicio_url'),
    path('agua',Agua.as_view(),name='agua_url'),
    path('productos',ProductoView.as_view(),name='productos_url'),
    path('kitiniciales',KitIniciales.as_view(),name='kitiniciales_url'),
    path('planes',Planes.as_view(),name='planes_url'), 
    path('dispacces',DispAcces.as_view(),name='dispacces_url'),
    path('lista',ListarTodosProductos.as_view(),name='listartodosproductos_url'),
    path('detalle/<int:pk>',ProductoDetalle.as_view(),name='detalle_url'),
    path('contacto', CrearContacto.as_view(),name='contacto_url'),
    path('succesfull',Succesfull.as_view(),name='successfull_url'),
    path('preguntas-frecuentes',PreguntasFrecuentes.as_view(),name='preguntasfrecuentes_url'),
    path('politicas-despacho',PoliticasDespacho.as_view(),name='politicasdespacho_url'),
    path('garantia',Garantia.as_view(),name='garantia_url'),
    path('zona-despacho',ZonaDespacho.as_view(),name='zonadespacho_url'),
    path('tratamiendo-de-aguas',TratamientoAguas.as_view(),name = 'tratamientoaguas_url'),
    path('iniciar-sesion', InicioSesion.as_view(),name='iniciosesion_url'),
    ]

ecopura_django/ecopura_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecopuraApp.urls')),
    path('registrar/',include('usuarios.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

ecopura_django/usuarios/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from usuarios.views import *

app_name = 'usuarios'
#APP_NAME ME SIRVE PARA PODER UTILIZAR EL REVERSE_LAZY, DICIENDOLE QUE APP VAMOS A USAR Y EL NOMBRE (name='contacto_url')
#DE LA URL A LA  QUE VAMOS REDIRECCIONAR
urlpatterns = [
    #PRIMER PARAMETRO PARA EL DIRECCIONAR CON URL, Y EL SEGUNDO ES EL NOMBRE DE LA FUNCION 
    #QUE ESTA EN LAS VISTAS (NO OLVIDAR IMPORTARLAS).
    path('',Registrar.as_view(),name='registrar_url'),
    path('registrado',RegistroExitoso.as_view(),name='registroexitoso_url'),
    path('login',IniciarSesion.as_view(),name='login_url'),
    path('logout',CerrarSesion.as_view(),name='logout_url')
    
]

ecopura_django/templates/agua.html
{% extends 'base.html'%}
{% load static%}
{% load humanize %}
{%block title%}
    Agua
{%endblock%}
{% block content%}

<img class="img-fluid w-100" src="{% static 'img/agua.png'%}" alt="">
{%include "lista.html"%}
{%endblock%}

ecopura_django/templates/dispacces.html
{% extends 'base.html'%}
{% load static%}
{%block title%}
    Kit Iniciales
{%endblock%}
{% block content%}
<img class="img-fluid w-100" src="{% static 'img/dispensadores-accesorios.png'%}" alt="">
{% include "lista.html"%}
{%endblock%}

ecopura_django/templates/footer.html
{%load static%}
<link rel="stylesheet" href="{%static '/css/footer.css' %}">
<footer>
    <div class="row px-0 mx-0">
        <div class="col-md">
            <h3>
                Horarios de reparto
            </h3>
            <p>
                Lunes a Viernes desde las 9:00 a las 19:00 hrs.
                y Sábado desde las 9:00 a las 19:00 hrs
            </p>
            <h3>
                Medios de Pago
            </h3>
            <p>Transferencia electronica</p>
            <p>Efectivo</p>
            <img class="img-fluid" src="../static/img/wevbpay.png" alt="">
        </div>
        <div class="col-md">
            <h3>
                Encuentranos en:
            </h3>
            <p>
                vicuña mackenna 1545 local 3 Peñaflor
            </p>
            <p>
                numero
            </p>
            <p>
                numero2
            </p>
            <p>
                ventas@ecopurachile.cl
            </p>
            <div id="redes" class="row mx-0">
                <a href=""><img src="../static/img/instagram.png" alt=""></a>
                <a href=""><img src="../static/img/facebook.png" alt=""></a>
                <a href=""><img src="../static/img/linkedin.png" alt=""></a>
            </div>
        </div>
        <div id='links-footer' class="col-md">
            <h3 class='pb-5'>
                <a href="" style="color:white">Políticas de despacho</a>
            </h3>
            <h3 class='pb-5'>
                <a href=""style="color:white">Garantía</a>
            </h3>
            <h3>
                <a href=""style="color:white">Preguntas frecuentes</a>
            </h3>
        </div>
    </div>
</footer>

ecopura_django/templates/formulario.html
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static%}
<link rel="stylesheet" href="{% static 'css/contacto.css'%}">


<form method="POST">
    {%csrf_token%}
    <div class="row py-0">
        <div class="col-md-6">
            {{form.p_nombre | as_crispy_field}}
        </div>
        <div class="col-md-6">
            {{form.p_apellido | as_crispy_field}}
        </div>
    </div>
    <div class="row py-0">
        <div class="col-md-6">
            {{form.empresa | as_crispy_field}}
        </div>
        <div class="col-md-6">
            {{form.telefono | as_crispy_field}}
        </div>
    </div>
    <div class="row py-0">
        <div class="col-md-6">
            {{form.rut_empresa | as_crispy_field}}
        </div>
        <div class="col-md-6">
            {{form.detalle_dispensador | as_crispy_field}}
        </div>
    </div>
    <div class="row py-0">
        <div class="col-md">
            {{form.correo | as_crispy_field}}
        </div>
    </div>
    <div class="row py-0 d-flex justify-content-center">
        <div class="col-md">
            {{form.detalle_texto | as_crispy_field}}
        </div>
    </div>
    <div class="row py-0 d-flex justify-content-center mt-3">  
        <input id="guardar_contacto"  type="submit" name="subrmit" value="Enviar">
    </div>
</form>

ecopura_django/templates/garantia.html
{% extends 'base.html'%}
{% load static%}

{%block title%}
    Garantía
{%endblock%}

{% block content%}
<img class="img-fluid" src="{% static 'img/garantia.png' %}" alt="">
<link rel="stylesheet" href="{% static 'css/garantia.css' %}">
<p>
    Nuestra política tiene una duración de hasta 6 meses para ejercer derecho a garantía sobre las compras realizadas en Ecopura SpA, por medios electrónicos, y en aquellos en que se aceptare una oferta realizada a través de catálogos, avisos, o cualquier otra forma de comunicación a distancia, no estarán sujetas al derecho de retracto. Esto en conformidad con el Artículo 3 º bis, letra b, de la Ley de Protección al Consumidor (Ley Nº 19496), y por lo tanto los clientes no podrán ejercer dicho derecho.
    <br>
    Es muy relevante que el cliente revise las dimensiones del producto y el lugar donde realizará la instalación. Las dimensiones estarán disponibles en todas las descripciones de nuestros productos. Su compra está sujeta a verificación, disponibilidad de stock y factibilidad de distribución a la dirección de despacho por usted indicada. Las fotos de los productos expuestos en sitio web son todas referenciales, lo valores no incluyen IVA 
    <br>
    En el caso, que el acuerdo entre Ecopura y el cliente sea cambio del producto, el o los artículos deben estar sin usar y en las mismas condiciones en que lo recibió el cliente. También debe estar en su embalaje original y contar con su boleta correspondiente.
    
    Productos no sujetos a garantía y/o a cambio o retornos serán:
    <br>
    * Tarjetas de regalo
    <br>
    * Productos entregados dado algún concurso realizado por la Empresa
    <br>
    * Algunos productos de salud y cuidado personal
    <br>
    Para solicitar garantía siempre requerimos un recibo o prueba de compra.
    <br>
    Por favor, no envíes tu compra de retorno a nuestra planta, se coordinará siempre con el cliente la forma en la que se procederá.
    <br>
    Hay algunas situaciones donde solo se pueden garantizar reembolsos parciales: (de ser aplicable)
    <br>
    * Cualquier ítem que no se encuentre en su condición original, que esté dañado o le falten partes por razones ajenas a nosotros.
    <br>
    * Cualquier ítem que sea haya sido aperturado o no cuente con sello de seguridad.
    <br>
     Reembolsos (donde aplique)
     <br>
    Una vez que tu devolución es recibida e inspeccionada, enviaremos un correo electrónico para notificarte que hemos recibido tu devolución. También te notificaremos la aprobación o rechazo de tu reembolso.
    <br>
    Si eres aprobado, entonces tu reembolso será procesado y un crédito será automáticamente aplicado a tu tarjeta de crédito o método original de pago, en una cierta cantidad de días. Los reembolsos serán aplicados de lunes a viernes entre 09.00 am y 14.00 pm.
    <br>
    Reembolsos tardíos o perdidos (donde aplique)
    <br>
    Si aún no has recibido tu reembolso, por favor chequea tu cuenta bancaria otra vez.
    <br>
    Luego contacta a tu compañía de tarjeta de crédito, puede tomar algún tiempo antes de que tu reembolso se postee oficialmente.
    <br>
    Próximo paso, contacta a tu banco.  A menudo pasa cierto tiempo antes de que tu reembolso se postee.
    <br>
    Si has seguido todos estos pasos y aún no haz recibido el reembolso, por favor contáctanos ventas@ecopurachile.cl
    <br>
    Intercambios o cambios de productos (donde aplique)
    <br>
    Solo reemplazamos artículos que estén defectuosos o dañados de fabrica.  Si necesitas cambiarlo por el mismo artículo, envíanos un correo electrónico a ventas@ecopurachile.cl
    <br>
    Se considerará que hay una falla o defecto:
    <br><br>
    a) Si los productos sujetos a normas de seguridad o calidad de cumplimiento obligatorio no cumplan las especificaciones correspondientes;
    <br>    b) Si los materiales, partes, piezas, elementos, sustancias o ingredientes que constituyan o integren los productos no correspondan a las especificaciones que ostenten o a las menciones del rotulado;
    <br>    c) Si cualquier producto, por deficiencias de fabricación, elaboración, materiales, partes, piezas, elementos, sustancias, ingredientes, estructura, calidad o condiciones sanitarias, en su caso, no sea enteramente apto para el uso o consumo al que está destinado o al que el proveedor hubiese señalado en su publicidad;
    <br>    d) Si el proveedor y consumidor hubieren convenido que los productos objeto del contrato deban reunir determinadas especificaciones y esto no ocurra;
    <br>    e) Si después de la primera vez de haberse hecho efectiva la garantía y prestado el servicio técnico correspondiente, subsistieren las deficiencias que hagan al bien inapto para el uso o consumo a que se refiere la letra c). Este derecho subsistirá para el evento de presentarse una deficiencia distinta a la que fue objeto del servicio técnico, o volviere a presentarse la misma, dentro de los plazos a que se refiere el artículo siguiente;
    <br>    f) Si la cosa objeto del contrato tenga defectos o vicios ocultos que imposibiliten el uso a que habitualmente se destine;
    <br>    g) Si la ley de los metales en los artículos de orfebrería, joyería y otros sea inferior a la que en ellos se indique. Para estos efectos se considerará que es un solo bien aquel que se ha vendido como un todo, aunque esté conformado por distintas unidades, partes, piezas o módulos, no obstante que éstas puedan o no prestar una utilidad en forma independiente unas de otras. Sin perjuicio de ello, tratándose de su reposición, ésta se podrá efectuar respecto de una unidad, parte, pieza o módulo, siempre que sea por otra igual a la que se restituye.
    <br><br>
    La Garantía o Cambio de los productos no será válida en los siguientes casos:
    <br><br>
    1. Por uso incorrecto o incumplimiento de las instrucciones contempladas en el Manual de Instrucciones de cada producto.
    <br>2. Cuando el producto haya sido utilizado en condiciones distintas a las normales y para lo que fue diseñado.
    <br>3. Desgaste normal de los accesorios, por efecto del uso o mal uso.
    <br>4. Desarme, reparación y/o alteración del producto por personas o talleres de servicios no autorizados por Sociedad Comercial Nailah Limitada.
    <br>5. Daños causados por agentes naturales, golpes, caídas, traslados, líquidos o polvos,etc.
    <br>6. No serán contemplados en la Garantía daños en los productos provocados por un golpe eléctrico de energía o por una instalación eléctrica deficiente o defectuosa en el hogar.
    <br><br>
     
    
    Envío
    <br>
    Para enviar el producto a servicio técnico, serás responsable por el pago de los costos de envío del artículo. Los costos de envío si los hubiere, no son reembolsables. Si recibes un reembolso, el costo del envío de la devolución será deducido de tu reembolso.
    <br>
    Dependiendo de dónde vivas, el tiempo que tome recibir el producto intercambiado, puede variar.
</p>
{%endblock%}

ecopura_django/templates/inicio.html
{% extends 'base.html'%}
{% load static%}
{%block title%}
Bienvenido a Ecopura
{%endblock%}

{% block content%}
<link rel="stylesheet" href="{%static 'css/inicio.css'%}">
<img id="img-1-responsive" class="img-fluid" src="{% static 'img/1-responsive.png'%}" alt="">
<img id="img-1" class="img-fluid w-100" src="{% static 'img/1.png'%}" alt="">
<div id="contenedor-promociones" class="container-fluid py-5 d-flex align-items-center justify-content-center">
  <h2 class="text-center display-4">PROMOCIONES ESPECIALES</h2>
</div>
<div id='img-2' class="row mx-auto d-flex justify-content-end">
  <div class="col">
    <h3 class="my-3">APROVECHA AHORA Y RECARGA TUS</h3>
    <h3 class="display-2 my-0">BOTELLONES</h3>
    <h3 class="my-3">DE 12 Y 20 LTS</h3>
    <a id="boton-productos" class="border border-white" href="">Ver productos</a>
  </div>
</div>
<div id="servicios" class="row my-5">
  <div class="col-md">
    <ul class="p-0">
      <li>
        <img class="img-fluid" src="{% static 'img/3-1.png'%}" alt="">
      </li>
      <li>
        <a href="">Agua</a>
      </li>
    </ul>
  </div>
  <div class="col-md">
    <ul>
      <li>
        <img class="img-fluid" src="{% static 'img/3-2.png'%}" alt="">
      </li>
      <li>
        <a href="">Kit iniciales</a>
      </li>
    </ul>
  </div>
  <div class="col-md">
    <ul>
      <li>
        <img class="img-fluid" src="{% static 'img/3-3.png'%}" alt="">
      </li>
      <li>
        <a href="">Planes</a>
      </li>
    </ul>
  </div>
  <div class="col-md">
    <ul>
      <li>
        <img class="img-fluid" src="{% static 'img/3-4.png'%}" alt="">
      </li>
      <li>
        <a href="">Accesorios</a>
      </li>
    </ul>
  </div>
</div>
<div id="informacion" class="row mx-auto">
  <div class="col-md">
    <ul>
      <li>
        <img class="img-fluid" src="{% static 'img/4-1.png'%}" alt="">
      </li>
      <li>
        <h3 class="text-center">Calidad Premium</h3>
      </li>
      <li>
        <p class="text-center">Nuestro equipo de profesionales consta de ingenieros químicos y especialistas en
          tratamiento
          de aguas</p>
      </li>
    </ul>
  </div>
  <div class="col-md">
    <ul>
      <li>
        <img class="img-fluid" src="{% static 'img/4-2.png'%}" alt="">
      </li>
      <li>
        <h3 class="text-center">Agua Purificada</h3>
      </li>
      <li>
        <p class="text-center">Nuestra agua Purificada es un tipo de Agua Potable donde las impurezas se reducen hasta
          tal punto que son casi imperceptibles</p>
      </li>
    </ul>
  </div>
  <div class="col-md">
    <ul>
      <li>
        <img class="img-fluid" src="{% static 'img/4-3.png'%}" alt="">
      </li>
      <li>
        <h3 class="text-center">Agua Alcalina</h3>
      </li>
      <li>
        <p class="text-center">Es un tipo de agua ionizada que actúa como un potente y natural antioxidante</p>
      </li>
    </ul>
  </div>

</div>
<div id="quienes" class="row py-5 px-0">
  <div class="col-md px-0">
    <img class="img-fluid" src="{% static 'img/5.png'%}" alt="">
  </div>
  <div id="quienes-somos" class="col-md">
    <h1 class="display-3 my-5">
      Quienes Somos
    </h1>
    <p>
      Ecopura SpA, es una empresa joven y dedicada a entregar
      productos y servicio de calidad garantizada con análisis y certificaciones constantes.
    </p>
    <a class="d-flex justify-content-center" href="">Ver más</a>
  </div>
</div>
<div id="contenedor-promociones" class="container-fluid d-flex align-items-center justify-content-center">
  <h2 class="text-center display-4 py-5 ">Productos Destacados</h2>
</div>
{%include "lista.html"%}
{%endblock%}

ecopura_django/templates/lista.html
{%load static%}
{% load humanize %}
<link rel="stylesheet" href="{% static 'css/lista.css'%}">
<div id="lista" class="row py-5 mx-auto">
    {% for producto in object_list%}
        <div class="col-sm pt-3">
            <div class="card border-0 mx-auto" style="width: 18rem;">
                <img class="card-img-top" src={{producto.foto}} alt="Card image cap">
                <div class="card-body py-0">
                    <span><h5 class="card-title text-center">{{producto.nombre}}</h5></span>
                    <div class="row px-5 pt-0">
                        <a class="text-center" href="{% url 'ecopuraApp:detalle_url' producto.id %}">${{producto.precio | intcomma}}</a>
                    </div>
                </div>
            </div>
        </div>
    {%endfor%}
  
    <div class="container-fluid">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"> < </a></li>
                {% endif %}
                {% for i in page_obj.paginator.page_range %}
                <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                {% endfor %}
                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">></a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

ecopura_django/templates/login.html
{% extends 'base.html'%}
{% load crispy_forms_filters%}
{% load crispy_forms_tags%}
{% load static%}
{%block title%}
Inicio Sesión
{%endblock%}
{% block content%}
<link rel="stylesheet" href="{% static 'css/login.css'%}">
<div class="row my-5 mx-0">
    <div class="col-md my-auto text-center">
            <h1>BIENVENIDO A ECOPURA</h1>
            <p>
                Te ayuda a comunicarte y compartir con las personas que forman parte de tu vida.
            </p>
    </div>
    <div class="col-md d-flex justify-content-start">
        <div class="card py-5 px-4">
            <form method="POST">
                {%csrf_token%}
                {{form.as_p}}
                <div class="col d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary">Iniciar Sesion</button>
                </div>
                <div class="card-body">¿No tienes cuenta? <a href="{% url 'usuarios:registrar_url'%}">Crear Cuenta</a></div>
            </form>
        </div>
    </div>
</div>


{%endblock%}

ecopura_django/templates/planes.html
{% extends 'base.html'%}
{% load static%}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{%block title%}
Planes
{%endblock%}

{% block content%}
<img class="img-fluid" src="{% static 'img/planes.png' %}" alt="">
<link rel="stylesheet" href="{% static 'css/planes.css' %}">
<div id="accordion">
  <div class="card">
    <button class="btn d-flex justify-content-start" data-toggle="collapse" data-target="#collapseOne"
      aria-expanded="true" aria-controls="collapseOne">
      <div class="row px-3 w-100">
        <div id="ac_sup" class="col-md-2 pl-3 d-flex justify-content-start">
          <h1>01</h1>
        </div>
        <div class="col-md-10 pl-3 d-flex justify-content-start">
          <h1>Plan básico</h1>
        </div>

      </div>
    </button>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
        Dispensador sobremesa ventilador, entrega agua fría y caliente al instante Incluye reposición mensual de 3
        bidones de 20 lts agua purificada Modelo de dispensador sujeto a stock
      </div>
    </div>
  </div>
  <div class="card">
    <button class="btn d-flex justify-content-start collapsed" data-toggle="collapse" data-target="#collapseTwo"
      aria-expanded="false" aria-controls="collapseTwo">
      <div class="row px-3 w-100">
        <div id="ac_sup" class="col-md-2 pl-3 d-flex justify-content-start">
          <h1>02</h1>
        </div>
        <div class="col-md-10 pl-3 d-flex justify-content-start">
          <h1>Plan Estándar</h1>
        </div>

      </div>
    </button>

    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body">
        Dispensador pedestal agua fría y caliente al instante Incluye reposición mensual de 5 bidones de 20 lts agua
        purificada Modelo de dispensador sujeto a stock.
      </div>
    </div>
  </div>
  <div class="card">
    <button class="btn d-flex justify-content-start collapsed" data-toggle="collapse" data-target="#collapseThree"
      aria-expanded="false" aria-controls="collapseThree">
      <div class="row px-3 w-100">
        <div id="ac_sup" class="col-md-2 pl-3 d-flex justify-content-start">
          <h1>03</h1>
        </div>
        <div class="col-md-10 pl-3 d-flex justify-content-start">
          <h1>Plan Premium</h1>
        </div>

      </div>
    </button>

    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
      <div class="card-body">
        Dispensador pedestal agua fría y caliente al instante Incluye reposición mensual de 10 bidones de 20 lts agua
        purificada Modelo de dispensador sujero a stock.
      </div>
    </div>
  </div>
  <div class="card">
    <div class="row px-3 w-100">
      <div id="ac_sup" class="col-md-2 pl-3 d-flex justify-content-start">
        <h1>04</h1>
      </div>
      <div class="col-md-10 pl-3 d-flex justify-content-start ">
        <h1>Plan Personalizado</h1>
      </div>

    </div>


    <div id="collapseTFour">
      <div class="card-body d-flex justify-content-center">

        {%include "formulario.html"%}
      </div>
    </div>
  </div>
</div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"></script>
{%endblock%}

ecopura_django/templates/politicas-despacho.html
{% extends 'base.html'%}
{% load static%}

{%block title%}
    Políticas de despacho
{%endblock%}

{% block content%}
<img class="img-fluid" src="{% static 'img/politicas-despacho.png' %}" alt="">
<link rel="stylesheet" href="{% static 'css/politicas-despacho.css' %}">
<ol>
    <li>Es muy relevante que el cliente revise las dimensiones del producto y el lugar donde realizará la instalación. Las dimensiones estarán disponibles en todas las descripciones de nuestros productos.</li>
    <li>Su compra está sujeta a verificación, disponibilidad de stock y factibilidad de distribución a la dirección de despacho por usted indicada.Las fotos de los productos expuestos en sitio web son todas referenciales, lo valores no incluyen IVA.</li>
    <li>Ecopura SpA realiza el despacho de productos de lunes a viernes, entre la 09:00 y las 19:00, y sábados entre las 09:00 y 19:00 sólo en comunas de la Región Metropolitana.</li>
    <li>Nuestro compromiso de entrega dependerá del destino del despacho, el plazo de entrega podrá ser de hasta 2 días hábiles desde el día hábil siguiente de la compra. Este plazo de entrega aplica sólo en las comunas de la Región Metropolitana</li>
    <li>Cada despacho que usted pague permite hasta 2 intentos de entrega en la dirección indicada por usted. En caso de no poder concretarse el despacho en ninguno de los 2 intentos, nuestro personal de Servicio al Cliente se contactará con usted para asistirlo. Esta entrega está sujeta a cobro y su valor será de hasta el 30% del valor de su compra.</li>
    <li>Al momento de la recepción, debe revisar visualmente el estado general su compra. La firma del cliente en el dispositivo electrónico del despachador será nuestra verificación de la conformidad en la recepción. En caso de que el producto sea recibido por un tercero (familiares, asesora del hogar, conserjes, mayordomo, etc.) se le solicitará a este firme en el dispositivo electrónico, Ecopura SpA entiende que el producto fue recibido a plena conformidad.</li>
    <li>Jamás lo visitaremos o contactaremos para solicitar retiro de productos que le hayamos despachado. Frente a un caso excepcional en que usted nos solicite retiro de un producto entregado por nosotros, deberá existir un acuerdo formal entre usted y nuestro Servicio de Atención a Clientes como respaldo. En este documento además se indicará si esta gestión presenta un costo para usted.</li>
    <li>La boleta de compraventa será enviada en forma electrónicaa través de e-mail a la casilla de correo electrónico informada.</li>
</ol>
{%endblock%}

ecopura_django/templates/producto_detalle.html
{% extends 'base.html'%}
{% load static%}
{% load humanize %}


{%block title%}
Planes
{%endblock%}

{% block content%}
<img class="img-fluid" src="{% static 'img/planes.png' %}" alt="">
<link rel="stylesheet" href="{% static 'css/detalles.css' %}">

<div class="row mx-0">
  <div id="col-izq" class="col-md">
    <img id="imagen-producto" class="img-fluid" src={{producto.foto.url}} alt="">
  </div>
  <div id="col-der" class="col-md text-center">
      <h3 class="mb-3"><strong>{{producto.nombre}}</strong></h3>
      <span class="display-5"><strong>${{object.precio | intcomma}}</strong></span>
      <br>
      <p class="mt-3">{{producto.descripcion}}</p>
  </div>
</div>
<div class="row mx-0 pb-3">
  <button type="button" class="btn btn-primary rounded-0">SOLICITAR</button>
</div>

{%endblock%}

ecopura_django/templates/productos.html
{% extends 'base.html'%}
{% load static%}
{%block title%}
    Productos
{%endblock%}
{% block content%}
<img class="img-fluid" src="../static/img/productos.png" alt="">
{%endblock%}

ecopura_django/templates/profile.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    
    <div class="container pt-5">
      <div class="d-flex justify-content-center">
        <form method="post">
          {% csrf_token %}
          {{ u_form.as_p}}
          {{ p_form.as_p}}
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>